bf16: true
cutoff_len: 10240
dataloader_num_workers: 4
dataset: evaluator_sft_data
ddp_timeout: 180000000
deepspeed: examples/deepspeed/ds_z3_config.json
do_train: true
finetuning_type: full
flash_attn: fa2
freeze_language_model: false
freeze_multi_modal_projector: true
freeze_vision_tower: true
gradient_accumulation_steps: 2
image_max_pixels: 802816
learning_rate: 1.0e-05
logging_steps: 10
lr_scheduler_type: cosine
max_samples: 100000
model_name_or_path: /your/path/to/model/Qwen/Qwen2.5-VL-3B-Instruct
num_train_epochs: 2
output_dir: /your/path/to/checkpoint/saves/easy_r1/experiment_name/SFT_models/round_init
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
resume_from_checkpoint: null
save_only_model: true
save_steps: 100000
seed: 42
stage: sft
template: qwen2_vl
train_img_dir: /path/to/data/train_data
trust_remote_code: true
val_size: 0
video_max_pixels: 16384
warmup_ratio: 0.1
